### ISSUE TITLE
Error while installing sparsify via pip

### ISSUE THREAD

**Issue by K-prog** [neuralmagic/sparsify#76]
While I was installing sparsify on Windows 10, via cmd using the command 'pip install sparsify' I encountered some errors :
![error_sparsify](https://user-images.githubusercontent.com/52241581/126708160-6e25fb5c-fef4-433a-8687-2828ab92f374.jpg)

After searching on google I found out that pysqlite3 was supported in Python2 and now is a part of the standard library in Python3, and needs no explicit installation via pip. I don't know what to do next and I am not able to use sparsify.

Python Version: 3.9.0
Pip Version: 21.1.3

**Comment by mpearce25** [comment]
The pysqlite3 dependency appears to be added by these lines: 
[https://github.com/neuralmagic/sparsify/blob/74b9682fae7a21f6bf1e8c60974266c0f368a6ae/setup.py#L66-L67](url)

Running `pip show sparsify` lists the requirements for sparsify as 
`Requires: sparseml, Flask-Cors, apispec, peewee, Flask, flasgger, marshmallow, pysqlite3-binary, sparsezoo`

If everything but the `pysqlite3-binary` packages is installed in your environment, a quick temporary workaround would be to use pip's `--no-dependencies` flag. This would effectively skip just the pysqlite3 package and should let you test sparsify until the issue is properly resolved. 

The full command would be: 
 
`pip install sparsify --no-dependencies`

**Comment by K-prog** [comment]
I used this command 'pip install sparsify --no-dependencies' and no other packages were installed
![image](https://user-images.githubusercontent.com/52241581/126750175-b693dcdb-f54e-4c91-9f53-f418f7549895.png)
![image](https://user-images.githubusercontent.com/52241581/126750208-6435a345-9701-49b2-8ee1-99019241f9d8.png)

Then I tried to manually  install the packages and then one more error occurred while installing sparseml:
![image](https://user-images.githubusercontent.com/52241581/126750748-e546f916-9401-48b8-848b-9172bea8fa56.png)
![image](https://user-images.githubusercontent.com/52241581/126750813-5a38c2b0-33a0-40a6-8f5e-8b2210262da3.png)

And one more thing, I checked the sparsify's setup.py file for pysqlite3 dependency [](https://github.com/neuralmagic/sparsify/blob/74b9682fae7a21f6bf1e8c60974266c0f368a6ae/setup.py#L66-L67)
Here, the problem should arise if the platform is linux or linux2 but I'm using Windows. So, why is it appearing?

**Comment by mpearce25** [comment]
The installation sections of sparsify and sparseml state that the code was tested on Linux/Debian systems and not Windows. Additionally, on the [DeepSparse](https://github.com/neuralmagic/deepsparse) readme it states "Mac and Windows require running Linux in a Docker or virtual machine". 

I would therefore try using a [linux Docker image](https://hub.docker.com/search?q=linux&type=image) or the [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by K-prog** [comment]
It is working fine with Windows Subsystem for Linux (WSL), thank you
